# Generated by Django 3.0.6 on 2020-05-18 18:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastAndRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast_or_roast', models.BooleanField()),
                ('title', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('down_votes', models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
